import { DAYS, CATEGORIES, dateKey } from '../Services/routineService'
export default function Statistics({ activities, sessions, dates }) {
  const keys = dates.map(dateKey)
  const weekSessions = sessions.filter(s => keys.includes(s.date))
  const totals = dates.map((date, index) => { const daily = activities.filter(a => a.days.includes(index)); return { total: daily.length, done: daily.filter(a => a.completedDates.includes(dateKey(date))).length } })
  const total = totals.reduce((sum, d) => sum + d.total, 0)
  const done = totals.reduce((sum, d) => sum + d.done, 0)
  const percent = total ? Math.round(done / total * 100) : 0
  const focus = weekSessions.filter(s => s.kind === 'focus').reduce((sum, s) => sum + s.seconds, 0)
  const rest = weekSessions.filter(s => s.kind === 'break').reduce((sum, s) => sum + s.seconds, 0)
  return <><div className="page-heading"><div><p className="eyebrow">CADA AVANCE CUENTA</p><h1>Rendimiento y ritmo ↗</h1><p>Tu progreso de esta semana, calculado a partir de tus actividades y sesiones.</p></div><span className="badge">Semana actual</span></div><div className="summary-grid">{[['Cumplimiento global', `${percent}%`], ['Enfoque acumulado', `${Math.floor(focus / 60)} min`], ['Completadas / pendientes', `${done} / ${total - done}`], ['Descanso acumulado', `${Math.floor(rest / 60)} min`]].map(([title, value]) => <div className="panel metric" key={title}><p>{title}</p><strong>{value}</strong></div>)}</div><div className="dashboard-grid"><section className="panel"><h2>Balance semanal de actividades</h2><p className="muted">Actividades completadas por día</p><div className="bar-chart">{totals.map((day, index) => <div className="bar-column" key={index}><span>{day.done}/{day.total}</span><div className="bar-track"><div className="bar-fill" style={{ height: `${day.total ? day.done / day.total * 100 : 0}%` }} /></div><small>{DAYS[index].slice(0, 3)}</small></div>)}</div></section><section className="panel"><h2>Distribución por categoría</h2><p className="muted">Actividades configuradas en tu rutina</p>{CATEGORIES.map(category => { const count = activities.filter(a => a.category === category).length; return <div className={`category-stat category-${category}`} key={category}><div><strong>{category}</strong><span>{count} actividades</span></div><progress value={count} max={activities.length || 1} aria-label={category} /></div> })}</section></div><section className="panel"><h2>▣ Almacenamiento local</h2><p className="muted">Tus actividades y sesiones se guardan en este navegador. Las sesiones de enfoque libre también cuentan en el tiempo acumulado.</p><p className="green">{sessions.length} sesiones registradas · {activities.length} actividades</p></section></>
}
