import { useState } from 'react'
import { DAYS, CATEGORIES, validateActivity } from '../Services/routineService'
export default function RoutineForm({ activity, onSave, onCancel }) {
  const [form, setForm] = useState(activity || { title: '', category: 'Programación', start: '09:00', end: '10:00', days: [0, 1, 2, 3, 4], reminder: '10' })
  const [error, setError] = useState('')
  function change(field, value) { setForm(previous => ({ ...previous, [field]: value })) }
  function submit(event) { event.preventDefault(); const message = validateActivity(form); setError(message); if (!message) onSave({ ...form, title: form.title.trim() }) }
  return <form className="panel editor" onSubmit={submit}><p className="eyebrow">DISEÑA TU RUTINA</p><h2>{activity ? 'Editar bloque' : 'Editor de bloque'}</h2><p className="muted">Dale un lugar a lo que importa.</p><label>Nombre de la actividad<input autoFocus={Boolean(activity)} value={form.title} onChange={e => change('title', e.target.value)} maxLength={100} required placeholder="Ej. Programación Frontend" /></label><fieldset><legend>Categoría del enfoque</legend><div className="category-options">{CATEGORIES.map(category => <button type="button" key={category} className={form.category === category ? 'selected' : ''} aria-pressed={form.category === category} onClick={() => change('category', category)}>{category}</button>)}</div></fieldset><div className="time-fields"><label>Hora inicial<input type="time" required value={form.start} onChange={e => change('start', e.target.value)} /></label><label>Hora final<input type="time" required value={form.end} onChange={e => change('end', e.target.value)} /></label></div><fieldset><legend>Días de repetición</legend><div className="day-options">{DAYS.map((day, index) => <button type="button" key={day} title={day} aria-label={day} aria-pressed={form.days.includes(index)} className={form.days.includes(index) ? 'selected' : ''} onClick={() => change('days', form.days.includes(index) ? form.days.filter(d => d !== index) : [...form.days, index])}>{day.slice(0, 2)}</button>)}</div></fieldset><label>Recordatorio<select value={form.reminder} onChange={e => change('reminder', e.target.value)}><option value="off">Sin recordatorio</option><option value="0">A la hora exacta</option>{[5, 10, 30].map(value => <option key={value} value={value}>{value} minutos antes</option>)}</select></label>{error && <p role="alert" className="error">{error}</p>}<div className="actions"><button className="primary" type="submit">{activity ? 'Guardar cambios' : '+ Guardar actividad'}</button><button type="button" onClick={onCancel}>{activity ? 'Cancelar' : 'Limpiar'}</button></div></form>
}
